---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "hitorro-jvs-example-springboot"
  labels:
    app.kubernetes.io/managed-by: "devportal"
    app: "hitorro-jvs-example-springboot"
spec:
  type: "NodePort"
  selector:
    app: "hitorro-jvs-example-springboot"
  ports:
  - name: "http"
    port: 8080
    targetPort: "http"
    protocol: "TCP"
    nodePort: 30000
